package org.zonarstudio.spraute_engine.script.function;

import java.util.HashMap;
import java.util.Map;

import org.zonarstudio.spraute_engine.script.function.SnapshotFunctions;

public class FunctionRegistry {
    private static final Map<String, ScriptFunction> FUNCTIONS = new HashMap<>();

    static {
        register(new ChatFunction());
        register(new LogFunction());
        register(new NpcFunction());
        register(new SayFunction());
        register(new GetNearestPlayerFunction());
        register(new SetNamesColorFunction());
        register(new GetSlotFunction());
        register(new HasItemFunction());
        register(new CountItemFunction());
        register(new ExecuteFunction());
        register(new TaskDoneFunction());
        register(new IntStrFunction("intStr"));
        register(new IntStrFunction("wholeStr"));
        register(new RandomFunction());
        register(new ParticleFunctions.Spawn());
        registerAlias("spawnParticle", new ParticleFunctions.Spawn());
        register(new ParticleFunctions.Line());
        register(new ParticleFunctions.Circle());
        register(new ParticleFunctions.Spiral());
        register(new ParticleFunctions.StartBone());
        register(new ParticleFunctions.StopBone());
        register(new OverlayOpenFunction());
        register(new OverlayCloseFunction());
        register(new ItemFunctions.GiveItem());
        register(new ItemFunctions.GetHeldItem());
        register(new UiOpenFunction());
        register(new UiCloseFunction());
        register(new UiUpdateFunction());
        register(new UiAnimateFunction());
        register(new ListFunctions.Create());
        register(new ListFunctions.ListAlias());
        register(new ListFunctions.Add());
        register(new ListFunctions.Get());
        register(new ListFunctions.Set());
        register(new ListFunctions.Size());
        register(new ListFunctions.Remove());
        register(new DictFunctions.Create());
        register(new DictFunctions.FromPairs());
        register(new DictFunctions.Set());
        register(new DictFunctions.Get());
        register(new DictFunctions.GetOr());
        register(new DictFunctions.Remove());
        register(new SpawnBillboardFunction());
        register(new StrLenFunction());
        register(new StrWidthFunction());
        register(new StrNewlineCountFunction());
        register(new SoundFunctions.PlaySound());
        register(new SoundFunctions.StopSound());
        register(new GetPlayerFunction());
        register(new SetBlockFunction());
        register(new BreakBlockAtFunction());
        registerAlias("break_block_at", new BreakBlockAtFunction());
        register(new SnapshotFunctions.SaveSnapshot());
        register(new SnapshotFunctions.LoadSnapshot());
        registerAlias("save_snapshot", new SnapshotFunctions.SaveSnapshot());
        registerAlias("load_snapshot", new SnapshotFunctions.LoadSnapshot());
        register(new JavaFunctions.JavaClassFunction());
        register(new JavaFunctions.JavaNewFunction());
        registerAlias("java_class", new JavaFunctions.JavaClassFunction());
        registerAlias("java_new", new JavaFunctions.JavaNewFunction());
        register(new JavaFunctions.SendPacketFunction());
        register(new SpawnOrbFunction());
        register(new RemoveOrbsFunction());
        register(new CancelEventFunction());
        register(new BlockDisplayFunctions.SetBlockDisplay());
        register(new BlockDisplayFunctions.SetBlockDisplayModel());
        register(new BlockDisplayFunctions.SetBlockDisplayBlock());
        register(new BlockDisplayFunctions.RemoveBlockDisplay());
        register(new BlockDisplayFunctions.OpenBlockUi());
        register(new BlockDisplayFunctions.GetBlockSlot());
        register(new ChestLootFunctions.SetChestLoot());
        register(new ChestLootFunctions.ClearChestLoot());
        register(new ChestLootFunctions.SetBlockSlot());
        register(new DropFunctions.AddMobDropFunction());
        register(new DropFunctions.AddBlockDropFunction());
        register(new ScriptManagementFunctions.StartScriptFunction());
        register(new ScriptManagementFunctions.StopScriptFunction());
        register(new FadeInFunction());
        register(new FadeOutFunction());
        register(new StopCameraFunction());
        register(new ResetCameraFunction());
        register(new CameraFunctions.SetCamera());
        register(new CameraFunctions.SetCameraLookAt());
        register(new CameraFunctions.AnimateCamera());
        register(new CameraFunctions.AnimateCameraLookAt());
        register(new CameraFunctions.CameraLookAt());
        register(new CameraFunctions.CameraWaypointTime());
        register(new CameraFunctions.CameraRouteStopAtPoint());
        registerAlias("camera_look_at", new CameraFunctions.CameraLookAt());
        registerAlias("camera_waypoint_time", new CameraFunctions.CameraWaypointTime());
        registerAlias("camera_route_stop_at_point", new CameraFunctions.CameraRouteStopAtPoint());
        registerAlias("set_camera", new CameraFunctions.SetCamera());
        registerAlias("set_camera_look_at", new CameraFunctions.SetCameraLookAt());
        registerAlias("animate_camera", new CameraFunctions.AnimateCamera());
        registerAlias("animate_camera_look_at", new CameraFunctions.AnimateCameraLookAt());
        registerAlias("stop_camera", new StopCameraFunction());
        registerAlias("reset_camera", new ResetCameraFunction());
        register(new PlayCameraRouteFunction());
        registerAlias("play_camera_route", new PlayCameraRouteFunction());
        register(new FindSafeBlockFunction());
        register(new PlaceStructureFunction());
        register(new WorldFunctions.TeleportToWorld());
        register(new WorldFunctions.GetWorldId());
        registerAlias("teleport_to_world", new WorldFunctions.TeleportToWorld());
        registerAlias("get_world_id", new WorldFunctions.GetWorldId());
        register(new SaveStructureFunction());
        // Entity utilities
        register(new EntityUtilFunctions.RemoveEntity());
        register(new EntityUtilFunctions.SetEntityGlowing());
        register(new EntityUtilFunctions.IsEntityGlowing());
        registerAlias("set_entity_glowing", new EntityUtilFunctions.SetEntityGlowing());
        registerAlias("entity_glow", new EntityUtilFunctions.SetEntityGlowing());
        registerAlias("is_entity_glowing", new EntityUtilFunctions.IsEntityGlowing());
        register(new EntityUtilFunctions.HealEntity());
        registerAlias("heal", new EntityUtilFunctions.HealEntity());
        register(new EntityUtilFunctions.ResetFallDistance());
        register(new EntityUtilFunctions.SetBillboardTexture());
        register(new EntityUtilFunctions.TeleportEntity());
        register(new EntityUtilFunctions.GetEntityPos());
        register(new EntityUtilFunctions.GetNpc());
        register(new EntityUtilFunctions.RegisterNpc());
        register(new EntityUtilFunctions.GetNearestNpc());
        registerAlias("get_npc", new EntityUtilFunctions.GetNpc());
        registerAlias("register_npc", new EntityUtilFunctions.RegisterNpc());
        registerAlias("get_nearest_npc", new EntityUtilFunctions.GetNearestNpc());
        // NPC groups
        register(new NpcGroupFunctions.CreateGroup());
        register(new NpcGroupFunctions.GetGroup());
        register(new NpcGroupFunctions.GroupAdd());
        register(new NpcGroupFunctions.GroupRemove());
        register(new NpcGroupFunctions.GroupClear());
        register(new NpcGroupFunctions.GroupSize());
        // Player list & tags
        register(new PlayerListFunctions.GetPlayers());
        register(new PlayerListFunctions.PlayerCount());
        register(new PlayerListFunctions.GetFirstPlayer());
        register(new PlayerListFunctions.GetLastPlayer());
        register(new PlayerListFunctions.GetPlayerAt());
        register(new PlayerTagFunctions.AddTag());
        register(new PlayerTagFunctions.RemoveTag());
        register(new PlayerTagFunctions.HasTag());
        register(new PlayerTagFunctions.GetByTag());
        register(new PlayerTagFunctions.GetTags());
        register(new PlayerMotionFunctions.GetPlayerMotion());
        register(new PlayerMotionFunctions.SetPlayerMotion());
        register(new PlayerMotionFunctions.AddPlayerMotion());
        registerAlias("get_player_motion", new PlayerMotionFunctions.GetPlayerMotion());
        registerAlias("set_player_motion", new PlayerMotionFunctions.SetPlayerMotion());
        registerAlias("add_player_motion", new PlayerMotionFunctions.AddPlayerMotion());
        registerAlias("getPlayerMoveVector", new PlayerMotionFunctions.GetPlayerMotion());
        registerAlias("setPlayerMoveVector", new PlayerMotionFunctions.SetPlayerMotion());
        registerAlias("get_player_move_vector", new PlayerMotionFunctions.GetPlayerMotion());
        registerAlias("set_player_move_vector", new PlayerMotionFunctions.SetPlayerMotion());
        register(new PlayerAttributeFunctions.GetMovementSpeed());
        register(new PlayerAttributeFunctions.SetMovementSpeed());
        register(new PlayerAttributeFunctions.GetJumpStrength());
        register(new PlayerAttributeFunctions.SetJumpStrength());
        register(new PlayerAttributeFunctions.GetStepHeight());
        register(new PlayerAttributeFunctions.SetStepHeight());
        register(new PlayerAttributeFunctions.GetAttackDamage());
        register(new PlayerAttributeFunctions.SetAttackDamage());
        register(new PlayerAttributeFunctions.GetDigSpeed());
        register(new PlayerAttributeFunctions.SetDigSpeed());
        registerAlias("get_player_movement_speed", new PlayerAttributeFunctions.GetMovementSpeed());
        registerAlias("set_player_movement_speed", new PlayerAttributeFunctions.SetMovementSpeed());
        registerAlias("get_player_jump_strength", new PlayerAttributeFunctions.GetJumpStrength());
        registerAlias("set_player_jump_strength", new PlayerAttributeFunctions.SetJumpStrength());
        registerAlias("get_player_step_height", new PlayerAttributeFunctions.GetStepHeight());
        registerAlias("set_player_step_height", new PlayerAttributeFunctions.SetStepHeight());
        registerAlias("get_player_attack_damage", new PlayerAttributeFunctions.GetAttackDamage());
        registerAlias("set_player_attack_damage", new PlayerAttributeFunctions.SetAttackDamage());
        registerAlias("get_player_dig_speed", new PlayerAttributeFunctions.GetDigSpeed());
        registerAlias("set_player_dig_speed", new PlayerAttributeFunctions.SetDigSpeed());
        register(new PlayerInventoryFunctions.GetItemInSlot());
        register(new PlayerInventoryFunctions.GetPlayerInventory());
        register(new PlayerInventoryFunctions.IsSlotEmpty());
        register(new PlayerInventoryFunctions.HasItemInSlot());
        register(new PlayerInventoryFunctions.FindItemSlot());
        register(new PlayerInventoryFunctions.SetItemInSlot());
        register(new PlayerInventoryFunctions.SetItemCount());
        register(new PlayerInventoryFunctions.ClearItemSlot());
        register(new PlayerInventoryFunctions.RemoveItem());
        register(new PlayerInventoryFunctions.GetItemName());
        register(new PlayerInventoryFunctions.SetItemName());
        register(new PlayerInventoryFunctions.GetItemLore());
        register(new PlayerInventoryFunctions.SetItemLore());
        register(new PlayerInventoryFunctions.AppendItemLore());
        register(new PlayerInventoryFunctions.GetItemAttackDamage());
        register(new PlayerInventoryFunctions.SetItemAttackDamage());
        register(new PlayerInventoryFunctions.GetItemNbt());
        register(new PlayerInventoryFunctions.SetItemNbt());
        registerAlias("get_item_in_slot", new PlayerInventoryFunctions.GetItemInSlot());
        registerAlias("get_player_inventory", new PlayerInventoryFunctions.GetPlayerInventory());
        registerAlias("is_slot_empty", new PlayerInventoryFunctions.IsSlotEmpty());
        registerAlias("has_item_in_slot", new PlayerInventoryFunctions.HasItemInSlot());
        registerAlias("find_item_slot", new PlayerInventoryFunctions.FindItemSlot());
        registerAlias("set_item_in_slot", new PlayerInventoryFunctions.SetItemInSlot());
        registerAlias("set_item_count", new PlayerInventoryFunctions.SetItemCount());
        registerAlias("clear_item_slot", new PlayerInventoryFunctions.ClearItemSlot());
        registerAlias("remove_item", new PlayerInventoryFunctions.RemoveItem());
        registerAlias("get_item_name", new PlayerInventoryFunctions.GetItemName());
        registerAlias("set_item_name", new PlayerInventoryFunctions.SetItemName());
        registerAlias("get_item_lore", new PlayerInventoryFunctions.GetItemLore());
        registerAlias("set_item_lore", new PlayerInventoryFunctions.SetItemLore());
        registerAlias("append_item_lore", new PlayerInventoryFunctions.AppendItemLore());
        register(new ItemRestrictionFunctions.ForbidItem());
        register(new ItemRestrictionFunctions.AllowItem());
        register(new ItemRestrictionFunctions.ClearItemRestrictions());
        register(new ItemRestrictionFunctions.IsItemForbidden());
        registerAlias("forbid_item", new ItemRestrictionFunctions.ForbidItem());
        registerAlias("allow_item", new ItemRestrictionFunctions.AllowItem());
        registerAlias("clear_item_restrictions", new ItemRestrictionFunctions.ClearItemRestrictions());
        registerAlias("is_item_forbidden", new ItemRestrictionFunctions.IsItemForbidden());
        registerAlias("get_item_attack_damage", new PlayerInventoryFunctions.GetItemAttackDamage());
        registerAlias("set_item_attack_damage", new PlayerInventoryFunctions.SetItemAttackDamage());
        registerAlias("get_item_nbt", new PlayerInventoryFunctions.GetItemNbt());
        registerAlias("set_item_nbt", new PlayerInventoryFunctions.SetItemNbt());
        register(new PlayerDirectionFunctions.GetPlayerFacing());
        registerAlias("get_player_facing", new PlayerDirectionFunctions.GetPlayerFacing());
        register(new AreaFunctions.PlayersInRadius());
        register(new AreaFunctions.PlayersNear());
        register(new AreaFunctions.EntitiesInRadius());
        register(new AreaFunctions.EntitiesNear());
        registerAlias("players_in_radius", new AreaFunctions.PlayersInRadius());
        registerAlias("players_near", new AreaFunctions.PlayersNear());
        registerAlias("entities_in_radius", new AreaFunctions.EntitiesInRadius());
        registerAlias("entities_near", new AreaFunctions.EntitiesNear());
        register(new TradeEventFunctions.FireTradeBuy());
        register(new TradeEventFunctions.FireTradeSell());
        register(new PlayerSkinFunctions.GetPlayerSkinUrl());
        register(new PlayerSkinFunctions.GetPlayerSkinTexture());
        register(new PlayerSkinFunctions.NpcSetPlayerSkin());
        register(new PlayerSkinFunctions.NpcClearPlayerSkin());
    }

    public static void register(ScriptFunction function) {
        FUNCTIONS.put(function.getName().toLowerCase(), function);
    }

    public static void registerAlias(String alias, ScriptFunction function) {
        FUNCTIONS.put(alias.toLowerCase(), function);
    }

    public static ScriptFunction get(String name) {
        return FUNCTIONS.get(name.toLowerCase());
    }

    public static boolean exists(String name) {
        return FUNCTIONS.containsKey(name.toLowerCase());
    }
}
